// <auto-generated />
using System;
using IdeaEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace IdeaEngine.Infrastructure.Migrations
{
    [DbContext(typeof(IdeaEngineDbContext))]
    [Migration("20260802050853_AddSignals")]
    partial class AddSignals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.AiLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.Property<long>("TokensIn")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_in");

                    b.Property<long>("TokensOut")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_out");

                    b.HasKey("Id")
                        .HasName("pk_ai_ledger");

                    b.HasIndex("Day", "Stage")
                        .HasDatabaseName("ix_ai_ledger_day_stage");

                    b.ToTable("ai_ledger", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.PipelineRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<int>("Errors")
                        .HasColumnType("integer")
                        .HasColumnName("errors");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("ItemsIn")
                        .HasColumnType("integer")
                        .HasColumnName("items_in");

                    b.Property<int>("ItemsOut")
                        .HasColumnType("integer")
                        .HasColumnName("items_out");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("notes");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_pipeline_runs");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_pipeline_runs_started_at");

                    b.ToTable("pipeline_runs", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.RawItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("author");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<string>("CommentsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("comments_json");

                    b.Property<string>("Community")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("community");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload_json");

                    b.Property<long>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("score");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_raw_items");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_raw_items_content_hash");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("ix_raw_items_fetched_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_raw_items_status");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_raw_items_source_external_id");

                    b.ToTable("raw_items", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.SignalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Audience")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("audience");

                    b.Property<string>("CommercialSentiment")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("commercial_sentiment");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<double>("Novelty")
                        .HasColumnType("double precision")
                        .HasColumnName("novelty");

                    b.Property<long>("RawItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_item_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_signals");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_signals_created_at");

                    b.HasIndex("RawItemId")
                        .HasDatabaseName("ix_signals_raw_item_id");

                    b.ToTable("signals", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.SignalEntity", b =>
                {
                    b.HasOne("IdeaEngine.Infrastructure.Persistence.Entities.RawItemEntity", "RawItem")
                        .WithMany()
                        .HasForeignKey("RawItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_signals_raw_items_raw_item_id");

                    b.Navigation("RawItem");
                });
#pragma warning restore 612, 618
        }
    }
}
