// <auto-generated />
using System;
using IdeaEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace IdeaEngine.Infrastructure.Migrations
{
    [DbContext(typeof(IdeaEngineDbContext))]
    [Migration("20260803022856_AddResearchArtifacts")]
    partial class AddResearchArtifacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.AiLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.Property<long>("TokensIn")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_in");

                    b.Property<long>("TokensOut")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_out");

                    b.HasKey("Id")
                        .HasName("pk_ai_ledger");

                    b.HasIndex("Day", "Stage")
                        .HasDatabaseName("ix_ai_ledger_day_stage");

                    b.ToTable("ai_ledger", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.AppStateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_app_state");

                    b.ToTable("app_state", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.IdeaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppealJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("appeal_json");

                    b.Property<string>("BuilderModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("builder_model");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DistributionNote")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("distribution_note");

                    b.Property<int>("EffortScale")
                        .HasColumnType("integer")
                        .HasColumnName("effort_scale");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_json");

                    b.Property<string>("Monetization")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("monetization");

                    b.Property<string>("NotesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("notes_json");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("origin");

                    b.Property<string>("OriginalPitch")
                        .HasColumnType("text")
                        .HasColumnName("original_pitch");

                    b.Property<string>("Playbook")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("playbook");

                    b.Property<string>("RelatedJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("related_json");

                    b.Property<string>("ScoresJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("scores_json");

                    b.Property<string>("SkepticJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("skeptic_json");

                    b.Property<string>("SkepticModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("skeptic_model");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("TargetUser")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("target_user");

                    b.Property<string>("Thesis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thesis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("VariantsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("variants_json");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id")
                        .HasName("pk_ideas");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ideas_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ideas_status");

                    b.HasIndex("Verified")
                        .HasDatabaseName("ix_ideas_verified");

                    b.ToTable("ideas", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.JobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("HoldUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hold_until");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<int?>("OriginMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_message_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int?>("ProgressMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("progress_message_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_jobs_status");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.PipelineRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<int>("Errors")
                        .HasColumnType("integer")
                        .HasColumnName("errors");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("ItemsIn")
                        .HasColumnType("integer")
                        .HasColumnName("items_in");

                    b.Property<int>("ItemsOut")
                        .HasColumnType("integer")
                        .HasColumnName("items_out");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("notes");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_pipeline_runs");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_pipeline_runs_started_at");

                    b.ToTable("pipeline_runs", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.RawItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("author");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<string>("CommentsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("comments_json");

                    b.Property<string>("Community")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("community");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload_json");

                    b.Property<long>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("score");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_raw_items");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_raw_items_content_hash");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("ix_raw_items_fetched_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_raw_items_status");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_raw_items_source_external_id");

                    b.ToTable("raw_items", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.ResearchArtifactEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("IdeaId")
                        .HasColumnType("bigint")
                        .HasColumnName("idea_id");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<long?>("ReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.HasKey("Id")
                        .HasName("pk_research_artifacts");

                    b.HasIndex("IdeaId")
                        .HasDatabaseName("ix_research_artifacts_idea_id");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_research_artifacts_kind");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_research_artifacts_report_id");

                    b.ToTable("research_artifacts", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.ResearchReportEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EngineVersion")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("engine_version");

                    b.Property<long>("IdeaId")
                        .HasColumnType("bigint")
                        .HasColumnName("idea_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("QueriesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("queries_json");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("report_json");

                    b.Property<int>("SearchesUsed")
                        .HasColumnType("integer")
                        .HasColumnName("searches_used");

                    b.Property<int>("SourcesCount")
                        .HasColumnType("integer")
                        .HasColumnName("sources_count");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_research_reports");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_research_reports_created_at");

                    b.HasIndex("IdeaId")
                        .HasDatabaseName("ix_research_reports_idea_id");

                    b.ToTable("research_reports", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.SignalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Audience")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("audience");

                    b.Property<string>("CommercialSentiment")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("commercial_sentiment");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Glance")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("glance");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<double>("Novelty")
                        .HasColumnType("double precision")
                        .HasColumnName("novelty");

                    b.Property<long>("RawItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_item_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_signals");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_signals_created_at");

                    b.HasIndex("RawItemId")
                        .HasDatabaseName("ix_signals_raw_item_id");

                    b.ToTable("signals", (string)null);
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.ResearchReportEntity", b =>
                {
                    b.HasOne("IdeaEngine.Infrastructure.Persistence.Entities.IdeaEntity", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_research_reports_ideas_idea_id");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("IdeaEngine.Infrastructure.Persistence.Entities.SignalEntity", b =>
                {
                    b.HasOne("IdeaEngine.Infrastructure.Persistence.Entities.RawItemEntity", "RawItem")
                        .WithMany()
                        .HasForeignKey("RawItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_signals_raw_items_raw_item_id");

                    b.Navigation("RawItem");
                });
#pragma warning restore 612, 618
        }
    }
}
